import { createClient, SupabaseClient } from '@supabase/supabase-js';

// UWAGA: Zastąp poniższe wartości rzeczywistymi danymi z Twojego projektu Supabase.
// Możesz je znaleźć w panelu administracyjnym Supabase w sekcji "Project Settings" -> "API".

const supabaseUrl = 'https://pihkjexqujborgqcrqly.supabase.co'; // Wklej tutaj swój Supabase URL
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpaGtqZXhxdWpib3JncWNycWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODA2MTMsImV4cCI6MjA3NDY1NjYxM30.lz5D8wV-wJYU1Qy8qV6LsHZzJU3UaUtfu6k3Vp6a_VA'; // Wklej tutaj swój klucz anonimowy (publiczny)

let supabase: SupabaseClient | null = null;

const isConfigured = supabaseUrl !== 'YOUR_SUPABASE_URL' && supabaseKey !== 'YOUR_SUPABASE_ANON_KEY' && supabaseUrl && supabaseKey;


if (isConfigured) {
  supabase = createClient(supabaseUrl, supabaseKey);
} else {
    console.warn(`
    ********************************************************************************
    * UWAGA: Klient Supabase nie jest skonfigurowany.                               *
    *                                                                              *
    * Otwórz plik 'lib/supabase.ts' i zastąp wartości 'YOUR_SUPABASE_URL'            *
    * oraz 'YOUR_SUPABASE_ANON_KEY' swoimi kluczami API projektu Supabase.           *
    * Bez tego zapisywanie e-maili nie będzie działać.                             *
    ********************************************************************************
  `);
}

export { supabase };

// Upewnij się, że masz tabelę o nazwie `subscribers` w swojej bazie danych Supabase.
// Możesz ją stworzyć za pomocą poniższego polecenia SQL w edytorze SQL Supabase:
/*
  CREATE TABLE public.subscribers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT now() NOT NULL
  );

  -- Włącz RLS (Row Level Security) dla tabeli
  ALTER TABLE public.subscribers ENABLE ROW LEVEL SECURITY;

  -- Stwórz politykę, która pozwala na publiczny zapis (INSERT) do tabeli
  CREATE POLICY "Public users can subscribe" ON public.subscribers
    FOR INSERT WITH CHECK (true);
*/
